swagger: "2.0"
info:
  title: cloud-run stg
  description: cloud run stg example
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

securityDefinitions:
  jwt:
    type: http
    scheme: bearer
    bearerFormat: JWT
security:
  - jwt: []

definitions:
  Error400:
    $ref: "./components/schemas/Error400.yaml"
  Error401:
    $ref: "./components/schemas/Error401.yaml"
  Error403:
    $ref: "./components/schemas/Error403.yaml"
  Error404:
    $ref: "./components/schemas/Error404.yaml"
  Error409AlreadyExist:
    $ref: "./components/schemas/Error409AlreadyExist.yaml"
  Error409UserNotExist:
    $ref: "./components/schemas/Error409UserNotExist.yaml"
  Error422:
    $ref: "./components/schemas/Error422.yaml"
  Error500:
    $ref: "./components/schemas/Error500.yaml"
paths:
  /user:
    $ref: "./paths_stg/user.yaml"