name: Deploy Express App to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: example-app
      PROJECT_ID: fir-example-9ece3
      SERVICE_ACCOUNT: example@fir-example-9ece3.iam.gserviceaccount.com

    permissions:
      contents: read
      id-token: write
      pages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build OpenAPI Documentation
        run: |
          docker run --rm -v ./docs:/docs jeanberu/swagger-cli swagger-cli bundle -t yaml -r /docs/openapi/openapi-stg.yaml -o /docs/openapi-to-deploy/openapi-to-deploy-stg.yaml

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     workload_identity_provider: https://iam.googleapis.com/projects/604131271753/locations/global/workloadIdentityPools/example-pool-id/providers/sdsad
      #     service_account: $SERVICE_ACCOUNT

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Set Google Cloud account
        run: gcloud config set account $SERVICE_ACCOUNT
     
      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 -t $IMAGE_NAME:latest .

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v major

      # - name: Push Docker Image to Artifact Registry
      #   env:
      #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      #   run: |-
      #     docker tag $IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
      #     docker tag $IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
      #     docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
      #     docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $IMAGE_NAME \
            --project $PROJECT_ID \
            --region asia-northeast1 \
            --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest \
            --platform managed \
            --service-account $SERVICE_ACCOUNT \
            --port 8080 \
            --quiet
